/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CodeforcesDailyChallengeInterface extends Interface {
    getFunction(nameOrSignature: "activeChallengeOf" | "cancelBeforeStart" | "challengeEndAt" | "createChallenge" | "getChallenge" | "getPeriodRecord" | "getPeriodWindow" | "markPeriodCompleted" | "nextChallengeId" | "oracle" | "outstandingPenaltyOf" | "owner" | "pause" | "paused" | "payPeriodPenalty" | "penaltyRecipient" | "renounceOwnership" | "setOracle" | "setPenaltyRecipient" | "setTreasury" | "slashPeriodNoOk" | "slashPeriodNoSubmission" | "transferOwnership" | "treasury" | "treasuryBalance" | "unpause" | "withdrawRemaining" | "withdrawTreasury"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ChallengeCanceled" | "ChallengeCreated" | "OracleUpdated" | "OwnershipTransferred" | "Paused" | "PenaltyPaid" | "PenaltyRecipientUpdated" | "PeriodCompleted" | "PeriodSlashed" | "RemainingWithdrawn" | "TreasuryUpdated" | "TreasuryWithdrawn" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'activeChallengeOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelBeforeStart', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'challengeEndAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createChallenge', values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getChallenge', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPeriodRecord', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPeriodWindow', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'markPeriodCompleted', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'nextChallengeId', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'outstandingPenaltyOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'payPeriodPenalty', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'penaltyRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setOracle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPenaltyRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'slashPeriodNoOk', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'slashPeriodNoSubmission', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawRemaining', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawTreasury', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'activeChallengeOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelBeforeStart', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'challengeEndAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createChallenge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getChallenge', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPeriodRecord', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPeriodWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markPeriodCompleted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextChallengeId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'outstandingPenaltyOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payPeriodPenalty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'penaltyRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPenaltyRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slashPeriodNoOk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slashPeriodNoSubmission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawRemaining', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTreasury', data: BytesLike): Result;
  }

  
    export namespace ChallengeCanceledEvent {
      export type InputTuple = [challengeId: BigNumberish, user: AddressLike, refundedAmount: BigNumberish];
      export type OutputTuple = [challengeId: bigint, user: string, refundedAmount: bigint];
      export interface OutputObject {challengeId: bigint, user: string, refundedAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ChallengeCreatedEvent {
      export type InputTuple = [challengeId: BigNumberish, user: AddressLike, handle: string, startAt: BigNumberish, periodDuration: BigNumberish, cycleDuration: BigNumberish, totalPeriods: BigNumberish, minRating: BigNumberish, penaltyNoSubmission: BigNumberish, penaltyNoOk: BigNumberish, deposit: BigNumberish];
      export type OutputTuple = [challengeId: bigint, user: string, handle: string, startAt: bigint, periodDuration: bigint, cycleDuration: bigint, totalPeriods: bigint, minRating: bigint, penaltyNoSubmission: bigint, penaltyNoOk: bigint, deposit: bigint];
      export interface OutputObject {challengeId: bigint, user: string, handle: string, startAt: bigint, periodDuration: bigint, cycleDuration: bigint, totalPeriods: bigint, minRating: bigint, penaltyNoSubmission: bigint, penaltyNoOk: bigint, deposit: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleUpdatedEvent {
      export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
      export type OutputTuple = [oldOracle: string, newOracle: string];
      export interface OutputObject {oldOracle: string, newOracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PenaltyPaidEvent {
      export type InputTuple = [challengeId: BigNumberish, periodIndex: BigNumberish, user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [challengeId: bigint, periodIndex: bigint, user: string, amount: bigint];
      export interface OutputObject {challengeId: bigint, periodIndex: bigint, user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PenaltyRecipientUpdatedEvent {
      export type InputTuple = [oldPenaltyRecipient: AddressLike, newPenaltyRecipient: AddressLike];
      export type OutputTuple = [oldPenaltyRecipient: string, newPenaltyRecipient: string];
      export interface OutputObject {oldPenaltyRecipient: string, newPenaltyRecipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PeriodCompletedEvent {
      export type InputTuple = [challengeId: BigNumberish, periodIndex: BigNumberish, submissionId: BigNumberish, acceptedAt: BigNumberish, rating: BigNumberish, proofHash: BytesLike];
      export type OutputTuple = [challengeId: bigint, periodIndex: bigint, submissionId: bigint, acceptedAt: bigint, rating: bigint, proofHash: string];
      export interface OutputObject {challengeId: bigint, periodIndex: bigint, submissionId: bigint, acceptedAt: bigint, rating: bigint, proofHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PeriodSlashedEvent {
      export type InputTuple = [challengeId: BigNumberish, periodIndex: BigNumberish, status: BigNumberish, penaltyApplied: BigNumberish, proofHash: BytesLike];
      export type OutputTuple = [challengeId: bigint, periodIndex: bigint, status: bigint, penaltyApplied: bigint, proofHash: string];
      export interface OutputObject {challengeId: bigint, periodIndex: bigint, status: bigint, penaltyApplied: bigint, proofHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RemainingWithdrawnEvent {
      export type InputTuple = [challengeId: BigNumberish, user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [challengeId: bigint, user: string, amount: bigint];
      export interface OutputObject {challengeId: bigint, user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
      export type OutputTuple = [oldTreasury: string, newTreasury: string];
      export interface OutputObject {oldTreasury: string, newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryWithdrawnEvent {
      export type InputTuple = [treasury: AddressLike, amount: BigNumberish];
      export type OutputTuple = [treasury: string, amount: bigint];
      export interface OutputObject {treasury: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CodeforcesDailyChallenge extends BaseContract {
    
    connect(runner?: ContractRunner | null): CodeforcesDailyChallenge;
    waitForDeployment(): Promise<this>;

    interface: CodeforcesDailyChallengeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activeChallengeOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    cancelBeforeStart: TypedContractMethod<
      [challengeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    challengeEndAt: TypedContractMethod<
      [challengeId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    createChallenge: TypedContractMethod<
      [handle: string, startAt: BigNumberish, periodDuration: BigNumberish, cycleDuration: BigNumberish, totalPeriods: BigNumberish, minRating: BigNumberish, penaltyNoSubmission: BigNumberish, penaltyNoOk: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    getChallenge: TypedContractMethod<
      [challengeId: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {user: string, handle: string, startAt: bigint, periodDuration: bigint, cycleDuration: bigint, totalPeriods: bigint, minRating: bigint, penaltyNoSubmission: bigint, penaltyNoOk: bigint, deposit: bigint, slashedAmount: bigint, resolvedPeriods: bigint, withdrawn: boolean, canceled: boolean, active: boolean }],
      'view'
    >
    

    
    getPeriodRecord: TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, ],
      [[bigint, bigint, bigint, boolean, bigint, bigint, bigint, string] & {status: bigint, resolvedAt: bigint, penaltyApplied: bigint, penaltySettled: boolean, submissionId: bigint, acceptedAt: bigint, rating: bigint, proofHash: string }],
      'view'
    >
    

    
    getPeriodWindow: TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, ],
      [[bigint, bigint] & {periodStart: bigint, periodEnd: bigint }],
      'view'
    >
    

    
    markPeriodCompleted: TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, submissionId: BigNumberish, acceptedAt: BigNumberish, rating: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    nextChallengeId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    outstandingPenaltyOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    payPeriodPenalty: TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    penaltyRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setOracle: TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPenaltyRecipient: TypedContractMethod<
      [newPenaltyRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    slashPeriodNoOk: TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    slashPeriodNoSubmission: TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    treasuryBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawRemaining: TypedContractMethod<
      [challengeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawTreasury: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activeChallengeOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelBeforeStart'): TypedContractMethod<
      [challengeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'challengeEndAt'): TypedContractMethod<
      [challengeId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createChallenge'): TypedContractMethod<
      [handle: string, startAt: BigNumberish, periodDuration: BigNumberish, cycleDuration: BigNumberish, totalPeriods: BigNumberish, minRating: BigNumberish, penaltyNoSubmission: BigNumberish, penaltyNoOk: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'getChallenge'): TypedContractMethod<
      [challengeId: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean, boolean] & {user: string, handle: string, startAt: bigint, periodDuration: bigint, cycleDuration: bigint, totalPeriods: bigint, minRating: bigint, penaltyNoSubmission: bigint, penaltyNoOk: bigint, deposit: bigint, slashedAmount: bigint, resolvedPeriods: bigint, withdrawn: boolean, canceled: boolean, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getPeriodRecord'): TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, ],
      [[bigint, bigint, bigint, boolean, bigint, bigint, bigint, string] & {status: bigint, resolvedAt: bigint, penaltyApplied: bigint, penaltySettled: boolean, submissionId: bigint, acceptedAt: bigint, rating: bigint, proofHash: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getPeriodWindow'): TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, ],
      [[bigint, bigint] & {periodStart: bigint, periodEnd: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'markPeriodCompleted'): TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, submissionId: BigNumberish, acceptedAt: BigNumberish, rating: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextChallengeId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'outstandingPenaltyOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'payPeriodPenalty'): TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'penaltyRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOracle'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPenaltyRecipient'): TypedContractMethod<
      [newPenaltyRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slashPeriodNoOk'): TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slashPeriodNoSubmission'): TypedContractMethod<
      [challengeId: BigNumberish, periodIndex: BigNumberish, proofHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawRemaining'): TypedContractMethod<
      [challengeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawTreasury'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ChallengeCanceled'): TypedContractEvent<ChallengeCanceledEvent.InputTuple, ChallengeCanceledEvent.OutputTuple, ChallengeCanceledEvent.OutputObject>;
getEvent(key: 'ChallengeCreated'): TypedContractEvent<ChallengeCreatedEvent.InputTuple, ChallengeCreatedEvent.OutputTuple, ChallengeCreatedEvent.OutputObject>;
getEvent(key: 'OracleUpdated'): TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PenaltyPaid'): TypedContractEvent<PenaltyPaidEvent.InputTuple, PenaltyPaidEvent.OutputTuple, PenaltyPaidEvent.OutputObject>;
getEvent(key: 'PenaltyRecipientUpdated'): TypedContractEvent<PenaltyRecipientUpdatedEvent.InputTuple, PenaltyRecipientUpdatedEvent.OutputTuple, PenaltyRecipientUpdatedEvent.OutputObject>;
getEvent(key: 'PeriodCompleted'): TypedContractEvent<PeriodCompletedEvent.InputTuple, PeriodCompletedEvent.OutputTuple, PeriodCompletedEvent.OutputObject>;
getEvent(key: 'PeriodSlashed'): TypedContractEvent<PeriodSlashedEvent.InputTuple, PeriodSlashedEvent.OutputTuple, PeriodSlashedEvent.OutputObject>;
getEvent(key: 'RemainingWithdrawn'): TypedContractEvent<RemainingWithdrawnEvent.InputTuple, RemainingWithdrawnEvent.OutputTuple, RemainingWithdrawnEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
getEvent(key: 'TreasuryWithdrawn'): TypedContractEvent<TreasuryWithdrawnEvent.InputTuple, TreasuryWithdrawnEvent.OutputTuple, TreasuryWithdrawnEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'ChallengeCanceled(uint256,address,uint256)': TypedContractEvent<ChallengeCanceledEvent.InputTuple, ChallengeCanceledEvent.OutputTuple, ChallengeCanceledEvent.OutputObject>;
      ChallengeCanceled: TypedContractEvent<ChallengeCanceledEvent.InputTuple, ChallengeCanceledEvent.OutputTuple, ChallengeCanceledEvent.OutputObject>;
    

      'ChallengeCreated(uint256,address,string,uint64,uint64,uint64,uint32,uint32,uint256,uint256,uint256)': TypedContractEvent<ChallengeCreatedEvent.InputTuple, ChallengeCreatedEvent.OutputTuple, ChallengeCreatedEvent.OutputObject>;
      ChallengeCreated: TypedContractEvent<ChallengeCreatedEvent.InputTuple, ChallengeCreatedEvent.OutputTuple, ChallengeCreatedEvent.OutputObject>;
    

      'OracleUpdated(address,address)': TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
      OracleUpdated: TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PenaltyPaid(uint256,uint256,address,uint256)': TypedContractEvent<PenaltyPaidEvent.InputTuple, PenaltyPaidEvent.OutputTuple, PenaltyPaidEvent.OutputObject>;
      PenaltyPaid: TypedContractEvent<PenaltyPaidEvent.InputTuple, PenaltyPaidEvent.OutputTuple, PenaltyPaidEvent.OutputObject>;
    

      'PenaltyRecipientUpdated(address,address)': TypedContractEvent<PenaltyRecipientUpdatedEvent.InputTuple, PenaltyRecipientUpdatedEvent.OutputTuple, PenaltyRecipientUpdatedEvent.OutputObject>;
      PenaltyRecipientUpdated: TypedContractEvent<PenaltyRecipientUpdatedEvent.InputTuple, PenaltyRecipientUpdatedEvent.OutputTuple, PenaltyRecipientUpdatedEvent.OutputObject>;
    

      'PeriodCompleted(uint256,uint256,uint256,uint256,uint256,bytes32)': TypedContractEvent<PeriodCompletedEvent.InputTuple, PeriodCompletedEvent.OutputTuple, PeriodCompletedEvent.OutputObject>;
      PeriodCompleted: TypedContractEvent<PeriodCompletedEvent.InputTuple, PeriodCompletedEvent.OutputTuple, PeriodCompletedEvent.OutputObject>;
    

      'PeriodSlashed(uint256,uint256,uint8,uint256,bytes32)': TypedContractEvent<PeriodSlashedEvent.InputTuple, PeriodSlashedEvent.OutputTuple, PeriodSlashedEvent.OutputObject>;
      PeriodSlashed: TypedContractEvent<PeriodSlashedEvent.InputTuple, PeriodSlashedEvent.OutputTuple, PeriodSlashedEvent.OutputObject>;
    

      'RemainingWithdrawn(uint256,address,uint256)': TypedContractEvent<RemainingWithdrawnEvent.InputTuple, RemainingWithdrawnEvent.OutputTuple, RemainingWithdrawnEvent.OutputObject>;
      RemainingWithdrawn: TypedContractEvent<RemainingWithdrawnEvent.InputTuple, RemainingWithdrawnEvent.OutputTuple, RemainingWithdrawnEvent.OutputObject>;
    

      'TreasuryUpdated(address,address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    

      'TreasuryWithdrawn(address,uint256)': TypedContractEvent<TreasuryWithdrawnEvent.InputTuple, TreasuryWithdrawnEvent.OutputTuple, TreasuryWithdrawnEvent.OutputObject>;
      TreasuryWithdrawn: TypedContractEvent<TreasuryWithdrawnEvent.InputTuple, TreasuryWithdrawnEvent.OutputTuple, TreasuryWithdrawnEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }