/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CodeforcesDailyChallenge__factory } from './CodeforcesDailyChallenge__factory.js';
export { MockToken__factory } from './MockToken__factory.js';